In [1]:
from google.colab import files
uploaded = files.upload()

Saving raw_marketing_data.csv to raw_marketing_data.csv

In [2]:
import pandas as pd

df = pd.read_csv('raw_marketing_data.csv')
df.head()

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Language,Clicks,Impressions,Engagement_Score,Customer_Segment,Date
0,1,Innovate Industries,Email,Men 18-24,30 days,Google Ads,0.04,"$16,174.00",6.29,Chicago,Spanish,506,1922,6,Health & Wellness,2021-01-01
1,2,NexGen Systems,Email,Women 35-44,60 days,Google Ads,0.12,"$11,566.00",5.61,New York,German,116,7523,7,Fashionistas,2021-01-02
2,3,Alpha Innovations,Influencer,Men 25-34,30 days,YouTube,0.07,"$10,200.00",7.18,Los Angeles,French,584,7698,1,Outdoor Adventurers,2021-01-03
3,4,DataTech Solutions,Display,All Ages,60 days,YouTube,0.11,"$12,724.00",5.55,Miami,Mandarin,217,1820,7,Health & Wellness,2021-01-04
4,5,NexGen Systems,Email,Men 25-34,15 days,YouTube,0.05,"$16,452.00",6.50,Los Angeles,Mandarin,379,4201,3,Health & Wellness,2021-01-05

In [3]:
df.columns.tolist()
df.info()
df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Campaign_ID       200000 non-null  int64
 1   Company           200000 non-null  object
 2   Campaign_Type     200000 non-null  object
 3   Target_Audience   200000 non-null  object
 4   Duration          200000 non-null  object
 5   Channel_Used      200000 non-null  object
 6   Conversion_Rate   200000 non-null  float64
 7   Acquisition_Cost  200000 non-null  object
 8   ROI               200000 non-null  float64
 9   Location          200000 non-null  object
 10  Language          200000 non-null  object
 11  Clicks            200000 non-null  int64
 12  Impressions       200000 non-null  int64
 13  Engagement_Score  200000 non-null  int64
 14  Customer_Segment  200000 non-null  object
 15  Date              200000 non-null  object
dtypes: float64(2), int64(4), object(10)
memory usage: 24.4+ MB

Campaign_ID         0
Company             0
Campaign_Type       0
Target_Audience     0
Duration            0
Channel_Used        0
Conversion_Rate     0
Acquisition_Cost    0
ROI                 0
Location            0
Language            0
Clicks              0
Impressions         0
Engagement_Score    0
Customer_Segment    0
Date                0
dtype: int64

In [4]:
df.columns = [c.strip().lower().replace(' ', '_') for c in df.columns]
df.head()

,campaign_id,company,campaign_type,target_audience,duration,channel_used,conversion_rate,acquisition_cost,roi,location,language,clicks,impressions,engagement_score,customer_segment,date
0,1,Innovate Industries,Email,Men 18-24,30 days,Google Ads,0.04,"$16,174.00",6.29,Chicago,Spanish,506,1922,6,Health & Wellness,2021-01-01
1,2,NexGen Systems,Email,Women 35-44,60 days,Google Ads,0.12,"$11,566.00",5.61,New York,German,116,7523,7,Fashionistas,2021-01-02
2,3,Alpha Innovations,Influencer,Men 25-34,30 days,YouTube,0.07,"$10,200.00",7.18,Los Angeles,French,584,7698,1,Outdoor Adventurers,2021-01-03
3,4,DataTech Solutions,Display,All Ages,60 days,YouTube,0.11,"$12,724.00",5.55,Miami,Mandarin,217,1820,7,Health & Wellness,2021-01-04
4,5,NexGen Systems,Email,Men 25-34,15 days,YouTube,0.05,"$16,452.00",6.50,Los Angeles,Mandarin,379,4201,3,Health & Wellness,2021-01-05

In [5]:
df.columns = [c.strip().lower() for c in df.columns]
df.columns

Index(['campaign_id', 'company', 'campaign_type', 'target_audience',
       'duration', 'channel_used', 'conversion_rate', 'acquisition_cost',
       'roi', 'location', 'language', 'clicks', 'impressions',
       'engagement_score', 'customer_segment', 'date'],
      dtype='object')

In [6]:
df['acquisition_cost'] = (
    df['acquisition_cost']
    .astype(str)
    .str.replace(r'[^0-9.]', '', regex=True)
)

df['acquisition_cost'] = pd.to_numeric(df['acquisition_cost'], errors='coerce')

In [7]:
df['channel_clean'] = (
    df['channel_used']
    .str.lower()
    .str.replace(r'fb|facebook', 'facebook', regex=True)
    .str.replace(r'ig|instagram', 'instagram', regex=True)
    .str.replace(r'google|adwords|ppc', 'google', regex=True)
    .str.replace(r'email|newsletter', 'email', regex=True)
)

In [8]:
df['ctr'] = df['clicks'] / df['impressions']
df['cpc'] = df['acquisition_cost'] / df['clicks']
df['cost_per_conversion'] = df['acquisition_cost'] / (df['conversion_rate'] * df['clicks'])

In [9]:
df['date'] = pd.to_datetime(df['date'])

In [10]:
df.to_csv('clean_marketing_data.csv', index=False)